config/routes.rb
Rails.application.routes.draw do
 root 'pages#index'
 get 'about', to: 'pages#about', as: 'person'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def about 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Me</h1>

<%= link_to "Home", root_path %>

app/views/pages/index.html.erb
<head>
	<title>Alpha Blog</title>
</head>



<body>

	<ul>
		<li>Home</li>
		<li>About</li>
		<li>People</li>
		<li>Sign Up</li>
		<li>Log In</li>
	</ul>

	<h1>Welcome to AlphaBlog!</h1>
	<h2>Start Your Own Blog!</h2>
	
	

	<p>Please let us know what you think</p>

	<div id="pics">
		<%= image_tag "group-of-kids.jpg" %>
		<%= image_tag "group-of-people.jpg" %>
		<%= image_tag "group-of-people-2.jpg" %>
	</div>
</body>

<div id="footer">
<footer>www.alphablog.com  *  (312)401-4570  *  <%= link_to "About Us", person_path %></footer>
</div>